AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates a ECR

Parameters:
  TagName:
    Description: Name of the tag
    Type: String
    AllowedPattern: ^[a-zA-Z0-9-]*$
    ConstraintDescription: Only alphanumeric values are allowed
  Value:
    Description: Name of the eenvironment
    Type: String
    AllowedPattern: ^[a-zA-Z0-9-]*$
    ConstraintDescription: Only alphanumeric values are allowed
Resources:
  TagBasedGroup:
    Type: "AWS::ResourceGroups::Group"
    Properties:
      Name: !Ref Value
      Description: "A group that is based on a tag query"
      ResourceQuery:
        Type:
          "TAG_FILTERS_1_0" 
        Query:
          ResourceTypeFilters: 
            - "AWS::AllSupported" 
          TagFilters:
            - 
              Key: !Ref TagName
              Values: 
                - !Ref Value