AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates a MySQL Aurora cluster in a single region

Parameters:
  EnvName:
    Description: An environment name that is prefixed to resource names
    Type: String
    AllowedPattern: ^[a-zA-Z0-9-]*$
    ConstraintDescription: Only alphanumeric values are allowed
  SecondaryRegion:
    Description: A region to replicate secret to
    Type: String
    Default: eu-west-1
    AllowedValues:
      - eu-west-1
      - eu-west-2
      - eu-west-3
Resources:

  MasterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${EnvName}'
      ReplicaRegions:
        - Region: !Ref SecondaryRegion
      Tags:
        - Key: Name
          Value: !Ref EnvName
        - Key: StackID
          Value: !Ref 'AWS::StackId'
      GenerateSecretString:
        SecretStringTemplate: '{"username":"dbadmin"}'
        GenerateStringKey: "password"
        ExcludeCharacters: '"!@#$%^&*/\+-,._~'
        PasswordLength: 16

Outputs:
  MasterSecret:
    Description: DB Secret
    Value: !Sub ${MasterSecret}
    Export:
      Name: !Sub '${EnvName}-MasterSecret'