AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates a ECR

Parameters:
  AppName:
    Description: Name of the repository
    Type: String
    AllowedPattern: ^[a-zA-Z0-9-]*$
    ConstraintDescription: Only alphanumeric values are allowed
Resources:
  ECR: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub '${AppName}'

Outputs:
  ECR:
    Description: DB Secret
    Value: !Ref ECR
    Export:
      Name: !Sub '${AppName}-ECR'
  RepositoryUri:
    Description: DB Secret
    Value: !GetAtt ECR.RepositoryUri
    Export:
      Name: !Sub '${AppName}-RepositoryUri'